doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13.0'
        charset: UTF8
        logging: false
        profiling: false
  orm:
    default_entity_manager: default

    entity_managers:
      default:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        connection: default
        auto_mapping: true
        mappings:
          common:
            type: annotation
            dir: '%kernel.project_dir%/src/Domain/Entity'
            is_bundle: false
            prefix: BackendTestApp\Domain\Entity
