###
GET http://localhost:6082/api/example?_order[id]=desc&_pageSize=10
X-USER-ID: 123

###
POST http://localhost:6082/api/example
Content-Type: application/json
X-USER-ID: 123

{"title":  "title", "description":  "description"}

###
PUT http://localhost:6082/api/example/1
Content-Type: application/json
X-USER-ID: 123

{"title":  "new title", "description":  "new description"}

###products

GET http://localhost:6082/api/product
X-USER-ID: 123


###
POST http://localhost:6082/api/product
Content-Type: application/json
X-USER-ID: 123

{"sku": "ssddsfo4fodf", "title": "product 2","price": 200, "qty": 1}

###
DELETE http://localhost:6082/api/product/11
Content-Type: application/json
X-USER-ID: 123


### Order
GET http://localhost:6082/api/order
X-USER-ID: 123

### create empty order
POST http://localhost:6082/api/order
Content-Type: application/json
X-USER-ID: 123

{}

### update order
PUT http://localhost:6082/api/order/1
Content-Type: application/json
X-USER-ID: 123

{}

### delete
DELETE http://localhost:6082/api/order/3
Content-Type: application/json
X-USER-ID: 123

### add to order
POST http://localhost:6082/api/addToOrder
Content-Type: application/json
X-USER-ID: 123

{"order_id": 10, "product_id": 26}

### delete item order
DELETE http://localhost:6082/api/removeItemOrder
Content-Type: application/json
X-USER-ID: 123

{"order_id": 10, "product_id": 24}

### delete item order
DELETE http://localhost:6082/api/removeItemById
Content-Type: application/json
X-USER-ID: 123

{"order_id": 10, "item_id": 8}

### delete all items
DELETE http://localhost:6082/api/removeAllItems/9
Content-Type: application/json
X-USER-ID: 123



